version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
          # context / project UI env-var reference
    steps:
      - checkout
      - run: docker login --username=fredmann1993 --password=Fi$ayo1993$
             
  test:
    docker:
      - image: cimg/base:2021.04
        # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test

