version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: DOCKER_USERNAME
          password: DOCKER_PASSWORD
          # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "HELLO" 
             
  

# Orchestrate our job run sequence

      

