version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
          # context / project UI env-var reference
    steps:
      - checkout
      - run: docker login --username=fredmann1993
             
  

# Orchestrate our job run sequence

      

